spring.application.name=tripnest-backend


spring.datasource.url=${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tripnest}}

spring.datasource.username=${DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:Vivek@1234}}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MySuperSecretKeyForTripnestApplication123456789
jwt.expiration=86400000

weather.api.key=9470ef085e2c95c12a3e103221c7013d
weather.api.url=https://api.openweathermap.org/data/2.5/weather

google.places.api.key=AIzaSyAue4OGy4gk5ELsPUp77_3KV1Qj_FTwxZE

# Spring Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:tripnest.travel.app@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:htrnxsexmybqcdla}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Frontend Configuration
app.frontend.base-url=${FRONTEND_BASE_URL:https://travel-planning-trip-management-platform-9lg1.onrender.com}
